- hosts: localhost
  gather_facts: false

  tasks:
    # Syntax check will pass whether or not the file exists
    - include_tasks: dates.yml

    # This will cause a failure since it can be checked statically
    - import_tasks: free.yml

    - name: Print a debug message
      debug:
        msg: "Hello from go deploy"