---
- hosts: localhost
  gather_facts: no

  vars:
    should_fail_via_fail: true
    should_fail_via_assert: false
    should_fail_via_complex_assert: false

  tasks:
    - name: Fail if conditions warrant a failure
      fail:
        msg: "Something went wrong"
      when: should_fail_via_fail

    - name: Stop playbook if an assertion isn't valid
      assert:
        that: "should_fail_via_assert != true"

    - name: Assertions can contain conditions
      assert:
        that:
          - should_fail_via_fail != true
          - should_fail_via_assert != true
          - should_fail_via_complex_assert != true